name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
      body:
        type: text
        description: Body text
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'default_pack${{ github.event.inputs.version }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "default_pack_${{ github.event.inputs.version }}.zip"
        tag: ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.body }}
        token: ${{ secrets.GITHUB_TOKEN }}
